// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	models "eduhub/server/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AttendanceService is an autogenerated mock type for the AttendanceService type
type AttendanceService struct {
	mock.Mock
}

// FreezeAttendance provides a mock function with given fields: ctx, collegeID, studentID
func (_m *AttendanceService) FreezeAttendance(ctx context.Context, collegeID int, studentID int) (bool, error) {
	ret := _m.Called(ctx, collegeID, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FreezeAttendance")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return rf(ctx, collegeID, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, collegeID, studentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FreezeStudent provides a mock function with given fields: ctx, collegeID, RollNo
func (_m *AttendanceService) FreezeStudent(ctx context.Context, collegeID int, RollNo string) error {
	ret := _m.Called(ctx, collegeID, RollNo)

	if len(ret) == 0 {
		panic("no return value specified for FreezeStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, collegeID, RollNo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateQRCode provides a mock function with given fields: ctx, collegeID, courseID, lectureID
func (_m *AttendanceService) GenerateQRCode(ctx context.Context, collegeID int, courseID int, lectureID int) (string, error) {
	ret := _m.Called(ctx, collegeID, courseID, lectureID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQRCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (string, error)); ok {
		return rf(ctx, collegeID, courseID, lectureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) string); ok {
		r0 = rf(ctx, collegeID, courseID, lectureID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, courseID, lectureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttendanceByCourse provides a mock function with given fields: ctx, collegeID, courseID
func (_m *AttendanceService) GetAttendanceByCourse(ctx context.Context, collegeID int, courseID int) ([]*models.Attendance, error) {
	ret := _m.Called(ctx, collegeID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByCourse")
	}

	var r0 []*models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Attendance, error)); ok {
		return rf(ctx, collegeID, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Attendance); ok {
		r0 = rf(ctx, collegeID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, collegeID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttendanceByLecture provides a mock function with given fields: ctx, collegeID, courseID, lectureID
func (_m *AttendanceService) GetAttendanceByLecture(ctx context.Context, collegeID int, courseID int, lectureID int) ([]*models.Attendance, error) {
	ret := _m.Called(ctx, collegeID, courseID, lectureID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByLecture")
	}

	var r0 []*models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.Attendance, error)); ok {
		return rf(ctx, collegeID, courseID, lectureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.Attendance); ok {
		r0 = rf(ctx, collegeID, courseID, lectureID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, courseID, lectureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttendanceByStudent provides a mock function with given fields: ctx, collegeID, studentID
func (_m *AttendanceService) GetAttendanceByStudent(ctx context.Context, collegeID int, studentID int) ([]*models.Attendance, error) {
	ret := _m.Called(ctx, collegeID, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByStudent")
	}

	var r0 []*models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Attendance, error)); ok {
		return rf(ctx, collegeID, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Attendance); ok {
		r0 = rf(ctx, collegeID, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttendanceByStudentAndCourse provides a mock function with given fields: ctx, collegeID, studentID, courseID
func (_m *AttendanceService) GetAttendanceByStudentAndCourse(ctx context.Context, collegeID int, studentID int, courseID int) ([]*models.Attendance, error) {
	ret := _m.Called(ctx, collegeID, studentID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByStudentAndCourse")
	}

	var r0 []*models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.Attendance, error)); ok {
		return rf(ctx, collegeID, studentID, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.Attendance); ok {
		r0 = rf(ctx, collegeID, studentID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAttendance provides a mock function with given fields: ctx, collegeID, studentID, courseID, lectureID
func (_m *AttendanceService) MarkAttendance(ctx context.Context, collegeID int, studentID int, courseID int, lectureID int) (bool, error) {
	ret := _m.Called(ctx, collegeID, studentID, courseID, lectureID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAttendance")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int) (bool, error)); ok {
		return rf(ctx, collegeID, studentID, courseID, lectureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int) bool); ok {
		r0 = rf(ctx, collegeID, studentID, courseID, lectureID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID, courseID, lectureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessQRCode provides a mock function with given fields: ctx, collegeID, studentID, qrCodeContent
func (_m *AttendanceService) ProcessQRCode(ctx context.Context, collegeID int, studentID int, qrCodeContent string) error {
	ret := _m.Called(ctx, collegeID, studentID, qrCodeContent)

	if len(ret) == 0 {
		panic("no return value specified for ProcessQRCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(ctx, collegeID, studentID, qrCodeContent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnFreezeStudent provides a mock function with given fields: ctx, collegeID, RollNo
func (_m *AttendanceService) UnFreezeStudent(ctx context.Context, collegeID int, RollNo string) error {
	ret := _m.Called(ctx, collegeID, RollNo)

	if len(ret) == 0 {
		panic("no return value specified for UnFreezeStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, collegeID, RollNo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAttendance provides a mock function with given fields: ctx, collegeID, studentID, courseID, lectureID, currentStatus, updatedStatus
func (_m *AttendanceService) UpdateAttendance(ctx context.Context, collegeID int, studentID int, courseID int, lectureID int, currentStatus string, updatedStatus string) (bool, error) {
	ret := _m.Called(ctx, collegeID, studentID, courseID, lectureID, currentStatus, updatedStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttendance")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int, string, string) (bool, error)); ok {
		return rf(ctx, collegeID, studentID, courseID, lectureID, currentStatus, updatedStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, int, string, string) bool); ok {
		r0 = rf(ctx, collegeID, studentID, courseID, lectureID, currentStatus, updatedStatus)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, int, string, string) error); ok {
		r1 = rf(ctx, collegeID, studentID, courseID, lectureID, currentStatus, updatedStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyStudentStateAndEnrollment provides a mock function with given fields: ctx, collegeID, studentID, courseID
func (_m *AttendanceService) VerifyStudentStateAndEnrollment(ctx context.Context, collegeID int, studentID int, courseID int) (bool, error) {
	ret := _m.Called(ctx, collegeID, studentID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyStudentStateAndEnrollment")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (bool, error)); ok {
		return rf(ctx, collegeID, studentID, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) bool); ok {
		r0 = rf(ctx, collegeID, studentID, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttendanceService creates a new instance of AttendanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceService {
	mock := &AttendanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
