// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	models "eduhub/server/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// EnrollmentRepository is an autogenerated mock type for the EnrollmentRepository type
type EnrollmentRepository struct {
	mock.Mock
}

// CreateEnrollment provides a mock function with given fields: ctx, enrollment
func (_m *EnrollmentRepository) CreateEnrollment(ctx context.Context, enrollment *models.Enrollment) error {
	ret := _m.Called(ctx, enrollment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Enrollment) error); ok {
		r0 = rf(ctx, enrollment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsStudentEnrolled provides a mock function with given fields: ctx, collegeID, studentID, courseID
func (_m *EnrollmentRepository) IsStudentEnrolled(ctx context.Context, collegeID int, studentID int, courseID int) (bool, error) {
	ret := _m.Called(ctx, collegeID, studentID, courseID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) bool); ok {
		r0 = rf(ctx, collegeID, studentID, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, collegeID, studentID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEnrollmentRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewEnrollmentRepository creates a new instance of EnrollmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEnrollmentRepository(t mockConstructorTestingTNewEnrollmentRepository) *EnrollmentRepository {
	mock := &EnrollmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
