// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SystemService is an autogenerated mock type for the SystemService type
type SystemService struct {
	mock.Mock
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *SystemService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSystemService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSystemService creates a new instance of SystemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSystemService(t mockConstructorTestingTNewSystemService) *SystemService {
	mock := &SystemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
